### ISSUE TITLE
my vtk files not working.

### ISSUE THREAD

**Issue by abhid28** [Helios113/vtkUnity#1]
Please see if these vtk files works. The test files work in my system. But the attached ones do not work. Both are separate files
[vtk2.zip](https://github.com/Helios113/vtkUnity/files/7234077/vtk2.zip)
[vtk1.zip](https://github.com/Helios113/vtkUnity/files/7234079/vtk1.zip)

**Comment by Helios113** [comment]
Hello,

Thanks for bringing this up. The issue occurs because your datasets don't have any vector or scalar fields, so the scripts don't know what to render. I will add on a feature which will let you render such data and I will post an update here. 

Thank you for using vtkUnity.

**Comment by Helios113** [comment]
Hello,

So after a better look, the issue turned out to be completely different. The files you provided are using polydata which is currently unsupported. This feature was something I've been meaning to add, so once I do that I will put another update.

Can I ask you what are you planning to use this project for?

Regards

**Comment by Helios113** [comment]
@abhid28 The new functionality is added. You will have the option to show vertices if needed. Keep in mind it will take a while to render all of them in 3D. Otherwise, the polygon data is rendered nicely. I also changed a few settings to make things easier for you with the setup. You can pull again and try the new version out.

**Comment by abhid28** [comment]
Hello  sir,
Thank you so much for the prompt reply and modified code. Please find the images. They are slightly different than  I get when I use https://kitware.github.io/itk-vtk-viewer. 

I am using lidar to get point clouds . Then I use this code https://pointclouds.org/documentation/tutorials/greedy_projection.html 

I need to view this output in hololens2. That is why I saved the pcl::PolygonMesh triangles in .vrt format and needed your code to  convert to unity supported file. Basically I have to view (constantly stream) the pcl::PolygonMesh triangles in hololens2. Can you advise on the best way to do so
![Bunny in kitware](https://user-images.githubusercontent.com/80229902/135025937-d0cd62fb-7b4b-4d4f-b745-eaecffd85913.PNG)
![Mines in unity](https://user-images.githubusercontent.com/80229902/135025939-c60388d4-280c-4811-8664-5db8418010ef.PNG)
![Bunny in unity](https://user-images.githubusercontent.com/80229902/135025942-3bffc3d6-f28e-47d1-8102-c637abbbd673.PNG)
![Mines in kitware](https://user-images.githubusercontent.com/80229902/135025943-0bcb8cbe-48dc-4650-8a24-db7c1d2420c2.PNG)
.

**Comment by Helios113** [comment]
Hello @abhid28 ,

So, I looked into your files and a few things popped up.
For your rabbit model, the vertex order of each polygon is sometimes flipped. Hence, it looks like the model is perforated. The easiest way to solve this is to enable two-sided rendering in your shader. The results will look like this.
For an unlit shader:
![unlit](https://user-images.githubusercontent.com/57684292/135076722-6ab618d2-56d1-430c-950d-3553baf59b3a.png)

And for a lit shader:

![lit](https://user-images.githubusercontent.com/57684292/135076769-9c4a6c31-425f-4250-b3b6-ea5f999cde4c.png)

The weird colors are due to shadows being cast incorrectly. There is no easy way to make this look nice in unity by just using shader manipulation. If you adjust the vertex order, the model will look correct with no extra adjustments.

For the other mesh, if you enable vertex renders you will get your result and it will look like this:

![vertex](https://user-images.githubusercontent.com/57684292/135077068-0d468a72-ffc4-434d-80c8-bbf00d29e278.png)

Again, this is not perfect because I currently make 3d objects at every vertex location. This is an issue with my code and I will look into making it better. The problem with having 3d objects at each vertex is that it makes everything very slow. If you need to render vertices in unity you might be better off making some 2d sprite at each vertex location. If you do end up doing it please add your code here and I will add it to the project.

Finally, for the rabbit model, try to flip the vertex order on the wrong polygons and it should work just fine.

**Comment by Helios113** [comment]
@abhid28 

I will try some other tricks to get the correct normal direction, but I cannot promise when it will be done or if it will work. I also opened your models with paraview and they looked fine. Paraview uses the same double-sided shader trick but has better/simpler lighting than unity, so you don't get the shadow issue.

My advice for you would be to use blender to load your models, make them look like you need them to and then export them to regular obj's with textures.
